export const colors = {
  transparent: 'transparent',
  primary: '#E392A1',
  buttonBgDisabled: '#E392A180',
  black: '#000000',
  gray: '#CECECE',
  dark_gray: '#8D8D8D',
  lightest_gray: '#F3F3F3',
  light_gray: '#F1F1F1',
  white: '#ffffff',
  orange: '#FF6161',
  lightPink_active: '#F1CED5',
  lightPink_second: '#F9E9EC',
  lightPink_third: '#FF94AB',
  lightPink_fourth: '#EAB5BF',
  light_brown: '#F5EBE0',
  success: '#489659',
  red: '#F73C3C',
  gradient_one: '#F0DBDB',
  gradient_second: '#DBA39A',
  blue: '#006BDF',
  border_color: '#949494',
  orange_second: '#FF9500',
  yellow: '#FFC732',
  disabled_button: '#D9D9D9',
  splash: '#FC4C62',
  gray_bg:'#EEEEEE',
  input_bg: "#D9D9D9",
  border: "#C6C6C6",
  orange_third: "#FF9500",
  second_text: "#767676",
  darkWhite: "#F8F8F8",
  lightPink_fifth: "#FAF5F1",
  border_second: "#efefef",
  doctor_bg: "#E6C0BB",
  black_fifty: "#3A3A3A50",
  border_payment: "#E6E6E6",
  light_gray_ECEBEB : "#ECEBEB",
};


export const FONTS = {
  Regular: "Montserrat-Regular",
  Black: "Montserrat-Black",
  SemiBold: "Montserrat-SemiBold",
  Bold: "Montserrat-Bold",
  ExtraBold: "Montserrat-ExtraBold",
  Light: "Montserrat-Light",
  Medium: "Montserrat-Medium",
  Thin: "Montserrat-Thin",
  ExtraLight: "Montserrat-ExtraLight",
  Montaga: "Montaga-Regular",
  Satisfy: "Satisfy-Regular",
};