//stacks
export const NAVIGATION_AUTH_LOADING_STACK = 'NAVIGATION_AUTH_LOADING_STACK';
export const NAVIGATION_AUTH_STACK = 'NAVIGATION_AUTH_STACK';
export const NAVIGATION_BOTTOM_TAB_STACK = 'NAVIGATION_BOTTOM_TAB_STACK';
//screens
export const NAVIGATION_AUTH_LOADING_SCREEN = 'NAVIGATION_AUTH_LOADING_SCREEN';
export const WELCOME_SCREEN = 'WELCOME_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const OTP_VERIFY_SCREEN = 'OTP_VERIFY_SCREEN';
export const HOME_SCREEN = 'HOME_SCREEN';
export const CALENDAR_SCREEN = 'CALENDAR_SCREEN';
export const NOTIFICATION_SCREEN = 'NOTIFICATION_SCREEN';
export const PROFILE_SCREEN = 'PROFILE_SCREEN';
export const PATIENT_SCREEN = 'PATIENT_SCREEN';
export const APPOINTMENT_SCREEN = 'APPOINTMENT_SCREEN';
export const EDIT_PROFILE_SCREEN = 'EDIT_PROFILE_SCREEN';
export const EXPERTS_SCREEN = 'EXPERTS_SCREEN';
export const REMARKS_SCREEN = 'REMARKS_SCREEN';
export const CALLING_SCREEN = 'CALLING_SCREEN';
export const SUBMIT_REPORT_SCREEN = 'SUBMIT_REPORT_SCREEN';
